version: 2.1

executors:
  ios:
    docker:
      - image: circleci/ios:latest

jobs:
  build:
    executor: ios
    steps:
      - checkout
      - run: echo "${DOCKER_USERNAME}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - run: echo "Building the iOS app"
      - run: echo "Tests pass"

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
