version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ios:latest

    environment:
      DOCKER_USERNAME: DOCKER_USERNAME
      DOCKER_PASSWORD: DOCKER_PASSWORD

    steps:
      - checkout

      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build and push Docker image
          command: |
            docker build -t myapp .
            docker tag myapp "$DOCKER_USERNAME/myapp:latest"
            docker push "$DOCKER_USERNAME/myapp:latest"
