version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ios:latest

    environment:
      DOCKER_USERNAME: << pipeline.environment.DOCKER_USERNAME >>
      DOCKER_PASSWORD: << pipeline.environment.DOCKER_PASSWORD >>

    steps:
      - checkout

      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/my-image .

      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKER_USERNAME/my-image
