version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ios:latest

    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}

    steps:
      - checkout

      - run:
          name: Log in to Docker Hub
          command: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - run:
          name: Build and test your iOS app
          command: xcodebuild test -scheme MyApp -destination "platform=iOS Simulator,OS=12.0,name=iPhone X"

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/ios:latest

    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}

    steps:
      - checkout

      - run:
          name: Log in to Docker Hub
          command: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - run:
          name: Deploy to the App Store
          command: fastlane deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
